### ISSUE TITLE
Problem with read adsTrain

### ISSUE THREAD

**Issue by Radziula7** [matlab-deep-learning/Fault-Detection-Using-Deep-Learning-Classification#3]
Hi,
I try use your project to undersand method LSTM. When i try run model DataPreparation I noticed that files ".dat" are not supported in read variable. 
![photo](https://user-images.githubusercontent.com/61599443/187049922-a7f64cd3-2389-4993-8f91-ed9eb785d540.PNG)
How I can change the code to pass first step in project?
Thanks

**Comment by junjiekoh** [comment]
yes i had the same issue too
![image](https://user-images.githubusercontent.com/98313079/188098021-22c8371a-c69d-4356-9324-e60e9434572c.png)
originally issue starts here, then solved after i added '.DAT' line10
now stuck at line16
![image](https://user-images.githubusercontent.com/98313079/188098317-b19ffee0-9015-4c9b-84fa-278a4bd09f53.png)

**Comment by junjiekoh** [comment]
Issue solved. Thank you very much!

**Comment by davidwillingham** [comment]
no problem!
